### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Delt06** [Delt06/unity-pcf-poisson#1]
https://wiki.epfl.ch/bachelorshadows/week3-4

- [x] Poisson Sampling
- [x] Stratified Poisson Sampling
- [x] Rotated Poisson Sampling
- [x] Renderer Feature
- [x] Disks of various sizes
- [x] Shadow fade
- [x] README

**Comment by Delt06** [comment]
https://wiki.epfl.ch/bachelorshadows/week3-4
